### ISSUE TITLE
Change header name 'React Meals' to 'Food to Go'

### ISSUE THREAD

**Issue by shree-1788** [CSI-CATT-DMCE/Food-To-Go#1]
<img width="1430" alt="Screen Shot 2022-10-16 at 6 32 15 PM" src="https://user-images.githubusercontent.com/87227032/196036952-87c3877a-f508-4360-be7a-c2302cd2cf84.png">

**Comment by Omkar-2003** [comment]
Could you assign this issue to me ?

**Comment by SarthakDeshmukh13** [comment]
_I would like to resolve this Issue._

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by chiragnc22** [comment]
Can you assign me this issue, please?

**Comment by MansiBhayade** [comment]
can you assign this issue to me ?
