### ISSUE TITLE
Add 3 fields of Dummy data in DUMMY_MEALS described in comments. (AvailableMeals.jsx)

### ISSUE THREAD

**Issue by shree-1788** [CSI-CATT-DMCE/Food-To-Go#2]
{
    id: "m5",
    name: "Yellow Bowl",
    description: "Fast...and Tasty...",
    price: 21.99,
  },
 {
    id: "m6",
    name: "Gazpacho",
    description: "A spanish delicacy",
    price: 8.99,
  },
 {
    id: "m7",
    name: "Croissant",
    description: "Buttery, flaky, French viennoiserie pastry",
    price: 12.99,
  },

**Comment by adi50920** [comment]
I would like to solve this issue.

**Comment by SarthakDeshmukh13** [comment]
_I would like to resolve this Issue._

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by adi50920** [comment]
can you please
 check and merge the code?
